### ISSUE TITLE
Resolving DNS servers

### ISSUE THREAD

**Issue by huntc** [ilya-epifanov/akka-dns#2]
I think we should be reading the list of DNS servers from `/etc/resolv.conf` by default. WDYT? I'm thinking that it is painful to have to declare the DNS servers for each service.

**Comment by huntc** [comment]
Just to let you know that I'm working on a PR for this right now.

**Comment by ilya-epifanov** [comment]
I've thought about it, but I intended this library to be used only for special cases and not as a replacement for default mechanism. If you think this might be a good idea, then we should definitely read resolv.conf. But we also need to read /etc/hosts to mimic default behavior.

Glad to hear you actually need this library:)

**Comment by huntc** [comment]
I've added a PR - see what you think: https://github.com/ilya-epifanov/akka-dns/pull/5
