### ISSUE TITLE
Min/Max TTL

### ISSUE THREAD

**Issue by lawrizs** [ilya-epifanov/akka-dns#8]
Hi,

I have an issue that a DNS does not get updated after I replace an instance of my service. Searching for an issue I found this that "max-positive-ttl" is used in two places below. This seams like a problem to me.

private val minPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)
private val maxPositiveTtl = config.getDuration("max-positive-ttl", TimeUnit.MILLISECONDS)

/Laurynas

**Comment by huntc** [comment]
Nice catch @lawrizs - any chance you could raise a PR?
